deploy:
  provider: heroku
  api_key:
    secure: ax/WkM7Q5cLjZAAUY/83+aWLOOHJdI46DBOJSvCzIXwx5AIwK00fkWx9OGKSLr0l1PMjEEbDk6pw2YAPLDDolmCG0udpwb6Xe7sGzFvRCzcoKhV9gCfL5je+ieVnk6juuCdQ7ep+zTqI0AmlkA+AGYq5ln33LShtX93YAdhDDiM6qv0cAmJKZ+/ozdRhnYeU7aqO7+TMPcqqLr3frchfyKbcqNESZeeNjW6lH6rCt0DT4DLRSUmrAiPFXL0cXXMcFip9wtCX7Ce3Dpf7OfdS8H36kqeGpFt9Uio4I5gObNLLxON8gqMQ3hdP3SgWgLB88DOPW55tSrurxzBFJm4ymdhbny+a2EWcx6q5Dib+fyldqn/yuHBJzF1Tr5p7lNhjsZ9HvEX85C0X37w6894xSqYS32qdXgs0UMb6mpjXDt03J0FBtlEWHkTjMkIH79hXQV3GIe6BCa1vieFoOeFTbFmDL05yzEmzDlmq5bcdoC7j995aj6Ki2OygtHpfDEMRSQ2JSI5wVUyFzN1nBc8TiRCYk2AOqtXGLCNYA4Pzdx0mRSkFZKzu/e3FKoD/P9V4Bd4a7yMhR7wINhPaYHDCs2nWtYV03pnSyYsgvetsb7TdURbahFBHK3REFtVOtzZuXVQ75cA/8o+t42LVAswb/Gm3JpqNtFicZSlZBh71zAU=
  app: heroku-bingo
  on:
    repo: MindricanRares/heroku-bingo
